rpg-project/config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :monsters
  resources :characters
  resources :weapons
  resources :vocations
  resources :secondaries
  resources :races
  post 'character/buyconfirm'
  get 'character/buy/:id', to: 'characters#buy'
  resources :helmets
  resources :armors
  devise_for :users, path: '', path_names: {
                                            sign_in: 'login',
                                            sign_up: 'register',
                                            sign_out: 'logout'
                                          }
  resources :companies
  resources :kinds

  # get 'home/index'
  # get 'home/chuchu', to: 'home#index'
  root 'home#index'

  resources :addresses
  resources :phones
  resources :kinds, except: [:destroy]
  # resources(:kinds, {:except => [:destroy, :update, :edit]})

  resources :pets, only: [:index, :show, :new, :edit]
  # resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rpg-project/app/models/armor.rb
class Armor < ApplicationRecord
	has_many :characters
end

rpg-project/app/models/character.rb
class Character < ApplicationRecord
	belongs_to :user
	belongs_to :weapon, required: false
	belongs_to :armor, required: false
	belongs_to :race
	belongs_to :secondary, required: false
	belongs_to :helmet, required: false
	belongs_to :race
	belongs_to :vocation

end

rpg-project/app/models/helmet.rb
class Helmet < ApplicationRecord
	has_many :characters
end

rpg-project/app/models/monster.rb
class Monster < ApplicationRecord
  belongs_to :vocation
  belongs_to :race
end

rpg-project/app/models/race.rb
class Race < ApplicationRecord
	has_many :characters
end

rpg-project/app/models/secondary.rb
class Secondary < ApplicationRecord
	has_many :characters
end

rpg-project/app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :vocation
end

rpg-project/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :characters, dependent: :destroy
  validates_presence_of :name
end

rpg-project/app/models/vocation.rb
class Vocation < ApplicationRecord
	has_many :characters
	has_many :skills
end

rpg-project/app/models/weapon.rb
class Weapon < ApplicationRecord
	has_many :characters
end

rpg-project/app/helpers/armors_helper.rb
module ArmorsHelper
end

rpg-project/app/helpers/characters_helper.rb
module CharactersHelper
end

rpg-project/app/helpers/helmets_helper.rb
module HelmetsHelper
end

rpg-project/app/helpers/home_helper.rb
module HomeHelper
end

rpg-project/app/helpers/monsters_helper.rb
module MonstersHelper
end

rpg-project/app/helpers/races_helper.rb
module RacesHelper
end

rpg-project/app/helpers/skills_helper.rb
module SkillsHelper
end

rpg-project/app/helpers/users_helper.rb
module UsersHelper
end

rpg-project/app/helpers/vocations_helper.rb
module VocationsHelper
end

rpg-project/app/helpers/weapons_helper.rb
module WeaponsHelper
end

rpg-project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ERRE PÊ GÊ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">RPG</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Armaduras', armors_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Helmos', helmets_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Races', races_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Equipamentos Secundários', secondaries_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Armas', weapons_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Vocações', vocations_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Monstros', monsters_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Habilidades', skills_path, class: 'nav-link' %>
            </li>
          </ul>

          <ul class="navbar-nav mr-0">
            <li class="nav-item">
              <%= link_to 'Seus personagens', characters_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <% if user_signed_in? %>
                <%= link_to "#{current_user.name} (Deslogar)", destroy_user_session_path, method: :delete, class: 'nav-link' %>        
              <% else %>
                <%= link_to 'Login', new_user_session_path, class: 'nav-link'  %>
              <% end %>
            </li>
          </ul>

        </div>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= msg %>
        <% end %>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>