rpg-project/config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :monsters
  resources :characters
  resources :weapons
  resources :vocations
  resources :secondaries
  resources :races
  post 'character/buyconfirm'
  get 'character/buy/:id', to: 'characters#buy'
  resources :helmets
  resources :armors
  devise_for :users, path: '', path_names: {
                                            sign_in: 'login',
                                            sign_up: 'register',
                                            sign_out: 'logout'
                                          }
  resources :companies
  resources :kinds

  # get 'home/index'
  # get 'home/chuchu', to: 'home#index'
  root 'home#index'

  resources :addresses
  resources :phones
  resources :kinds, except: [:destroy]
  # resources(:kinds, {:except => [:destroy, :update, :edit]})

  resources :pets, only: [:index, :show, :new, :edit]
  # resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rpg-project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rpg-project/app/models/armor.rb
class Armor < ApplicationRecord
	has_many :characters
end

rpg-project/app/models/character.rb
class Character < ApplicationRecord
	belongs_to :user
	belongs_to :weapon, required: false
	belongs_to :armor, required: false
	belongs_to :race
	belongs_to :secondary, required: false
	belongs_to :helmet, required: false
	belongs_to :race
	belongs_to :vocation

end

rpg-project/app/models/helmet.rb
class Helmet < ApplicationRecord
	has_many :characters
end

rpg-project/app/models/monster.rb
class Monster < ApplicationRecord
  belongs_to :vocation
  belongs_to :race
end

rpg-project/app/models/race.rb
class Race < ApplicationRecord
	has_many :characters
end

rpg-project/app/models/secondary.rb
class Secondary < ApplicationRecord
	has_many :characters
end

rpg-project/app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :vocation
end

rpg-project/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :characters, dependent: :destroy
  validates_presence_of :name
end

rpg-project/app/models/vocation.rb
class Vocation < ApplicationRecord
	has_many :characters
	has_many :skills
end

rpg-project/app/models/weapon.rb
class Weapon < ApplicationRecord
	has_many :characters
end

rpg-project/app/controllers/secondaries_controller.rb
class SecondariesController < ApplicationController
  before_action :set_secondary, only: [:show, :edit, :update, :destroy]

  # GET /secondaries
  # GET /secondaries.json
  def index
    @secondaries = Secondary.all
  end

  # GET /secondaries/1
  # GET /secondaries/1.json
  def show
  end

  # GET /secondaries/new
  def new
    if current_user.kind == 1
    @secondary = Secondary.new
    else
      not_authorized
    end
  end

  # GET /secondaries/1/edit
  def edit
    if current_user.kind == 0
      not_authorized
    end
  end

  # POST /secondaries
  # POST /secondaries.json
  def create
    @secondary = Secondary.new(secondary_params)

    respond_to do |format|
      if @secondary.save
        format.html { redirect_to @secondary, notice: 'Secondary was successfully created.' }
        format.json { render :show, status: :created, location: @secondary }
      else
        format.html { render :new }
        format.json { render json: @secondary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /secondaries/1
  # PATCH/PUT /secondaries/1.json
  def update
    respond_to do |format|
      if @secondary.update(secondary_params)
        format.html { redirect_to @secondary, notice: 'Secondary was successfully updated.' }
        format.json { render :show, status: :ok, location: @secondary }
      else
        format.html { render :edit }
        format.json { render json: @secondary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secondaries/1
  # DELETE /secondaries/1.json
  def destroy
    if current_user.kind == 1
      @secondary.destroy
      respond_to do |format|
        format.html { redirect_to secondaries_url, notice: 'Secondary was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      not_authorized
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_secondary
      @secondary = Secondary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def secondary_params
      params.require(:secondary).permit(:armor, :damage, :dex_requirement, :int_requirement, :name, :str_requirement, :value)
    end
end

rpg-project/app/helpers/armors_helper.rb
module ArmorsHelper
end

rpg-project/app/helpers/characters_helper.rb
module CharactersHelper
end

rpg-project/app/helpers/helmets_helper.rb
module HelmetsHelper
end

rpg-project/app/helpers/home_helper.rb
module HomeHelper
end

rpg-project/app/helpers/monsters_helper.rb
module MonstersHelper
end

rpg-project/app/helpers/races_helper.rb
module RacesHelper
end

rpg-project/app/helpers/secondaries_helper.rb
module SecondariesHelper
end

rpg-project/app/helpers/skills_helper.rb
module SkillsHelper
end

rpg-project/app/helpers/users_helper.rb
module UsersHelper
end

rpg-project/app/helpers/vocations_helper.rb
module VocationsHelper
end

rpg-project/app/helpers/weapons_helper.rb
module WeaponsHelper
end

rpg-project/app/views/secondaries/_form.html.erb
<%= simple_form_for(@secondary) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :armor %>
    <%= f.input :damage %>
    <%= f.input :dex_requirement %>
    <%= f.input :int_requirement %>
    <%= f.input :name %>
    <%= f.input :str_requirement %>
    <%= f.input :value %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

rpg-project/app/views/secondaries/edit.html.erb
<div class="page-header">
  <%= link_to secondaries_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @secondary, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing secondary</h1>
</div>

<%= render 'form' %>

rpg-project/app/views/secondaries/index.html.erb
<div class="page-header">
  <h1>Listing secondaries</h1>
  <%= link_to new_secondary_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Secondary
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Armor</th>
            <th>Damage</th>
            <th>Dex requirement</th>
            <th>Int requirement</th>
            <th>Name</th>
            <th>Str requirement</th>
            <th>Value</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @secondaries.each do |secondary| %>
        <tr>
            <td><%= secondary.armor %></td>
            <td><%= secondary.damage %></td>
            <td><%= secondary.dex_requirement %></td>
            <td><%= secondary.int_requirement %></td>
            <td><%= secondary.name %></td>
            <td><%= secondary.str_requirement %></td>
            <td><%= secondary.value %></td>
            <td><%= link_to 'Show', secondary %></td>
        <td><%= link_to 'Edit', edit_secondary_path(secondary) %></td>
        <td><%= link_to 'Destroy', secondary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

rpg-project/app/views/secondaries/new.html.erb
<div class="page-header">
  <%= link_to secondaries_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New secondary</h1>
</div>

<%= render 'form' %>

rpg-project/app/views/secondaries/show.html.erb
<div class="page-header">
  <%= link_to secondaries_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_secondary_path(@secondary), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show secondary</h1>
</div>

<dl class="dl-horizontal">
  <dt>Armor:</dt>
  <dd><%= @secondary.armor %></dd>

  <dt>Damage:</dt>
  <dd><%= @secondary.damage %></dd>

  <dt>Dex requirement:</dt>
  <dd><%= @secondary.dex_requirement %></dd>

  <dt>Int requirement:</dt>
  <dd><%= @secondary.int_requirement %></dd>

  <dt>Name:</dt>
  <dd><%= @secondary.name %></dd>

  <dt>Str requirement:</dt>
  <dd><%= @secondary.str_requirement %></dd>

  <dt>Value:</dt>
  <dd><%= @secondary.value %></dd>

</dl>