rpg-project/config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :monsters
  resources :characters
  resources :weapons
  resources :vocations
  resources :secondaries
  resources :races
  post 'character/buyconfirm'
  get 'character/buy/:id', to: 'characters#buy'
  resources :helmets
  resources :armors
  devise_for :users, path: '', path_names: {
                                            sign_in: 'login',
                                            sign_up: 'register',
                                            sign_out: 'logout'
                                          }
  resources :companies
  resources :kinds

  # get 'home/index'
  # get 'home/chuchu', to: 'home#index'
  root 'home#index'

  resources :addresses
  resources :phones
  resources :kinds, except: [:destroy]
  # resources(:kinds, {:except => [:destroy, :update, :edit]})

  resources :pets, only: [:index, :show, :new, :edit]
  # resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rpg-project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rpg-project/app/models/armor.rb
class Armor < ApplicationRecord
	has_many :characters
end

rpg-project/app/models/character.rb
class Character < ApplicationRecord
	belongs_to :user
	belongs_to :weapon, required: false
	belongs_to :armor, required: false
	belongs_to :race
	belongs_to :secondary, required: false
	belongs_to :helmet, required: false
	belongs_to :race
	belongs_to :vocation

end

rpg-project/app/models/helmet.rb
class Helmet < ApplicationRecord
	has_many :characters
end

rpg-project/app/models/monster.rb
class Monster < ApplicationRecord
  belongs_to :vocation
  belongs_to :race
end

rpg-project/app/models/race.rb
class Race < ApplicationRecord
	has_many :characters
end

rpg-project/app/models/secondary.rb
class Secondary < ApplicationRecord
	has_many :characters
end

rpg-project/app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :vocation
end

rpg-project/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :characters, dependent: :destroy
  validates_presence_of :name
end

rpg-project/app/models/vocation.rb
class Vocation < ApplicationRecord
	has_many :characters
	has_many :skills
end

rpg-project/app/models/weapon.rb
class Weapon < ApplicationRecord
	has_many :characters
end

rpg-project/app/controllers/helmets_controller.rb
class HelmetsController < ApplicationController
  before_action :set_helmet, only: [:show, :edit, :update, :destroy]

  # GET /helmets
  # GET /helmets.json
  def index
    @helmets = Helmet.all
  end

  # GET /helmets/1
  # GET /helmets/1.json
  def show
  end
  # GET /helmets/new
  def new
    if current_user.kind == 1
    @helmet = Helmet.new
    else
      not_authorized
    end
  end

  # GET /helmets/1/edit
  def edit
    if current_user.kind == 0
      not_authorized
    end
  end

  # POST /helmets
  # POST /helmets.json
  def create
    @helmet = Helmet.new(helmet_params)

    respond_to do |format|
      if @helmet.save
        format.html { redirect_to @helmet, notice: 'Helmet was successfully created.' }
        format.json { render :show, status: :created, location: @helmet }
      else
        format.html { render :new }
        format.json { render json: @helmet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /helmets/1
  # PATCH/PUT /helmets/1.json
  def update
    respond_to do |format|
      if @helmet.update(helmet_params)
        format.html { redirect_to @helmet, notice: 'Helmet was successfully updated.' }
        format.json { render :show, status: :ok, location: @helmet }
      else
        format.html { render :edit }
        format.json { render json: @helmet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /helmets/1
  # DELETE /helmets/1.json
  def destroy
    if current_user.kind == 1
      @helmet.destroy
      respond_to do |format|
        format.html { redirect_to helmets_url, notice: 'Helmet was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      not_authorized
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_helmet
      @helmet = Helmet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def helmet_params
      params.require(:helmet).permit(:armor, :cons_requirement, :int_bonus, :int_requirement, :name, :str_requirement, :value, :character_id)
    end
end

rpg-project/app/helpers/application_helper.rb
module ApplicationHelper
end

rpg-project/app/helpers/armors_helper.rb
module ArmorsHelper
end

rpg-project/app/helpers/characters_helper.rb
module CharactersHelper
end

rpg-project/app/helpers/helmets_helper.rb
module HelmetsHelper
end

rpg-project/app/helpers/home_helper.rb
module HomeHelper
end

rpg-project/app/helpers/monsters_helper.rb
module MonstersHelper
end

rpg-project/app/helpers/races_helper.rb
module RacesHelper
end

rpg-project/app/helpers/skills_helper.rb
module SkillsHelper
end

rpg-project/app/helpers/users_helper.rb
module UsersHelper
end

rpg-project/app/helpers/vocations_helper.rb
module VocationsHelper
end

rpg-project/app/helpers/weapons_helper.rb
module WeaponsHelper
end

rpg-project/app/views/helmets/_form.html.erb
<%= simple_form_for(@helmet) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :armor %>
    <%= f.input :cons_requirement %>
    <%= f.input :int_bonus %>
    <%= f.input :int_requirement %>
    <%= f.input :name %>
    <%= f.input :str_requirement %>
    <%= f.input :value %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

rpg-project/app/views/helmets/edit.html.erb
<div class="page-header">
  <%= link_to helmets_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @helmet, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing helmet</h1>
</div>

<%= render 'form' %>

rpg-project/app/views/helmets/index.html.erb
<div class="page-header">
  <h1>Listing helmets</h1>
  <%= link_to new_helmet_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Helmet
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Armor</th>
            <th>Cons requirement</th>
            <th>Int bonus</th>
            <th>Int requirement</th>
            <th>Name</th>
            <th>Str requirement</th>
            <th>Value</th>
            <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @helmets.each do |helmet| %>
        <tr>
            <td><%= helmet.armor %></td>
            <td><%= helmet.cons_requirement %></td>
            <td><%= helmet.int_bonus %></td>
            <td><%= helmet.int_requirement %></td>
            <td><%= helmet.name %></td>
            <td><%= helmet.str_requirement %></td>
            <td><%= helmet.value %></td>
            <td><%= link_to 'Show', helmet %></td>
        <td><%= link_to 'Edit', edit_helmet_path(helmet) %></td>
        <td><%= link_to 'Destroy', helmet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

rpg-project/app/views/helmets/new.html.erb
<div class="page-header">
  <%= link_to helmets_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New helmet</h1>
</div>

<%= render 'form' %>

rpg-project/app/views/helmets/show.html.erb
<div class="page-header">
  <%= link_to helmets_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_helmet_path(@helmet), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show helmet</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @helmet.name %></dd>
  <dt>Armor:</dt>
  <dd><%= @helmet.armor %></dd>
  <dt>Value:</dt>
  <dd><%= @helmet.value %></dd>

  <dt>Cons requirement:</dt>
  <dd><%= @helmet.cons_requirement %></dd>

  <dt>Int bonus:</dt>
  <dd><%= @helmet.int_bonus %></dd>

  <dt>Int requirement:</dt>
  <dd><%= @helmet.int_requirement %></dd>

  <dt>Str requirement:</dt>
  <dd><%= @helmet.str_requirement %></dd>

</dl>